// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJEZ_ajPeXRKm_XSP3yalAm24tVVhpQT0',
    appId: '1:178833870932:web:bf7cf71e8df65e631e9dc1',
    messagingSenderId: '178833870932',
    projectId: 'jeff-test-33065',
    authDomain: 'jeff-test-33065.firebaseapp.com',
    storageBucket: 'jeff-test-33065.appspot.com',
    measurementId: 'G-WT9SCY0LPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzEhqvHT11k75c3UQGVC8Fllf0pAnP8Zo',
    appId: '1:178833870932:android:34ba532bb42304271e9dc1',
    messagingSenderId: '178833870932',
    projectId: 'jeff-test-33065',
    storageBucket: 'jeff-test-33065.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIDB21p3ZhD-78RSS1wEmwLV-CUasG04k',
    appId: '1:178833870932:ios:785302b18ce637bf1e9dc1',
    messagingSenderId: '178833870932',
    projectId: 'jeff-test-33065',
    storageBucket: 'jeff-test-33065.appspot.com',
    iosClientId: '178833870932-rhbnv8omo0kk1i8pf5e93ld8u9999r0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJeffreyDev',
  );
}
